version: 2

jobs:
    build:
        working_directory: ~/secure-eval
        docker:
            - image: circleci/node:8.9.3
        steps:
            - checkout
            - run:
                name: Set permissions
                command: sudo chown -R circleci /usr/local/lib/node_modules
            - run:
                name: Install Electron dependencies
                command: sudo apt-get update && sudo apt-get install xvfb && sudo apt-get install libgtk2.0-0 && sudo apt-get install libxtst6 && sudo apt-get install libXss1 && sudo apt-get install Libgconf-2-4 && sudo apt-get install libnss3 && sudo apt-get install libasound2
            - run: npm install
            - run: npm test
